### Register request
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "loforney",
  "password": "pass"
}

### Login request
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "loforney",
  "password": "pass"
}

<> 2023-05-03T155523.200.json
### Create new posting
POST http://localhost:5000/posting
Content-Type: application/json

{
  "title": "Ad title",
  "description": "Ad title long description",
  "category": "jobs"
}

### Get all listings
GET http://localhost:5000/posting

<> 2023-05-03T160209.200.json
### Get specific listing (id is the last argument)
GET http://localhost:5000/posting/6452cb99d177b07cf40cf053

### Get by category (it searches by the key "category")
GET http://localhost:5000/posting/category
Category: "forsale/

